# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  schedule:
    - cron: "*/60 * * * *"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python gate.py
      - name: set global name
        run: git config --global user.name "mat"
      - name: set global email
        run: git config --global user.email "mitus11112@gmail.com"
      - name: switching from HTTPS to SSH
        run: git remote set-url origin https://github.com/mitus1212/Listings-Bot.git
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating listingi.db"
      - name: pull from main
        run: git pull origin main
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main